gui:
  # If true, show the number of lines changed per file in the Files view
  showNumstatInFilesView: true

  # If true, allow scrolling past the bottom of the content in the main window
  scrollPastBottom: false

  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: "3"

  # How things are filtered when typing '/'.
  # One of 'substring' (default) | 'fuzzy'
  filterMode: fuzzy

  # Whether to show the divergence from the base branch in the branches view.
  # One of: 'none' | 'onlyArrow'  | 'arrowAndNumber'
  showDivergenceFromBaseBranch: arrowAndNumber

  # Format used when displaying time e.g. commit time.
  # Uses Go's time format syntax: https://pkg.go.dev/time#Time.Format
  timeFormat: 2006-01-02

  authorColors:
    # use red for John Smith
    'Ryan Ulep': 'blue'
    # use blue for other authors
    '*': 'default'

  theme:
    selectedLineBgColor:
      - white

git:
  pagers:
    # TODO: For some reason, this delta command is not working
    - pager: delta --line-numbers --hyperlinks --hyperlinks-file-link-format=lazygit-edit://{path}:{line}

# If true, exit Lazygit when the user presses escape in a context where there is
# nothing to cancel/close
quitOnTopLevelReturn: true

os:
  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      printf "\033Ptmux;\033\033]52;c;$(printf {{text}} | base64 -w 0)\a\033\\" > /dev/tty
    else
      printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty
    fi
